import { BusinessDetails, PostWithBusiness, Comment } from '@/types';

// Sample image URLs using placeholder services
const SAMPLE_IMAGES = {
    coffee: [
        'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800&h=600&fit=crop',
        'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&h=600&fit=crop',
        'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&h=600&fit=crop',
    ],
    food: [
        'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&h=600&fit=crop',
        'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800&h=600&fit=crop',
        'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&h=600&fit=crop',
    ],
    sushi: [
        'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=800&h=600&fit=crop',
        'https://images.unsplash.com/photo-1583623025817-d180a2221d0a?w=800&h=600&fit=crop',
    ],
    spa: [
        'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800&h=600&fit=crop',
        'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&h=600&fit=crop',
    ],
    fashion: [
        'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=800&h=600&fit=crop',
        'https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=800&h=600&fit=crop',
        'https://images.unsplash.com/photo-1558171813-4c088753af8f?w=800&h=600&fit=crop',
        'https://images.unsplash.com/photo-1445205170230-053b83016050?w=800&h=600&fit=crop',
    ],
    gym: [
        'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&h=600&fit=crop',
        'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800&h=600&fit=crop',
    ],
    music: [
        'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&h=600&fit=crop',
        'https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=800&h=600&fit=crop',
    ],
    books: [
        'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=800&h=600&fit=crop',
    ],
};

// Sample video URL (using a public sample)
const SAMPLE_VIDEO = 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4';
const SAMPLE_VIDEO_THUMBNAIL = 'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=800&h=600&fit=crop';

// Mock businesses around a central location (New York City area)
export const MOCK_BUSINESSES: BusinessDetails[] = [
    {
        id: 'b1',
        profile_id: 'p1',
        business_name: 'The Coffee Lab',
        bio: 'Artisan coffee roasters serving the finest single-origin beans. Try our signature cold brew!',
        category: 'Cafe',
        latitude: 40.7128,
        longitude: -74.006,
        address: '123 Main Street, New York, NY',
        phone: '+1 (555) 123-4567',
        is_premium: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: 'b2',
        profile_id: 'p2',
        business_name: 'Bella Italia',
        bio: 'Authentic Italian cuisine made with imported ingredients. Family recipes passed down for generations.',
        category: 'Restaurant',
        latitude: 40.7145,
        longitude: -74.0035,
        address: '456 Oak Avenue, New York, NY',
        phone: '+1 (555) 234-5678',
        is_premium: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: 'b3',
        profile_id: 'p3',
        business_name: 'FitZone Gym',
        bio: '24/7 fitness center with state-of-the-art equipment and personal trainers.',
        category: 'Health & Beauty',
        latitude: 40.7105,
        longitude: -74.0085,
        address: '789 Fitness Boulevard, New York, NY',
        phone: '+1 (555) 345-6789',
        is_premium: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: 'b4',
        profile_id: 'p4',
        business_name: 'TechHub Electronics',
        bio: 'Your one-stop shop for all electronics and gadgets. Expert repairs and great prices!',
        category: 'Retail',
        latitude: 40.7158,
        longitude: -74.0095,
        address: '321 Digital Drive, New York, NY',
        phone: '+1 (555) 456-7890',
        is_premium: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: 'b5',
        profile_id: 'p5',
        business_name: 'Zen Spa & Wellness',
        bio: 'Relax and rejuvenate with our premium spa treatments. Massages, facials, and more.',
        category: 'Health & Beauty',
        latitude: 40.7095,
        longitude: -74.0045,
        address: '555 Serenity Lane, New York, NY',
        phone: '+1 (555) 567-8901',
        is_premium: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: 'b6',
        profile_id: 'p6',
        business_name: 'Urban Threads',
        bio: 'Trendy fashion boutique featuring local designers and sustainable clothing.',
        category: 'Retail',
        latitude: 40.7168,
        longitude: -74.0025,
        address: '777 Style Street, New York, NY',
        phone: '+1 (555) 678-9012',
        is_premium: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: 'b7',
        profile_id: 'p7',
        business_name: 'Sushi Master',
        bio: 'Fresh sushi and Japanese cuisine prepared by master chefs. Omakase available.',
        category: 'Restaurant',
        latitude: 40.7115,
        longitude: -74.0015,
        address: '888 Tokyo Way, New York, NY',
        phone: '+1 (555) 789-0123',
        is_premium: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: 'b8',
        profile_id: 'p8',
        business_name: 'Quick Fix Auto',
        bio: 'Fast and reliable auto repairs. Oil changes, brakes, and full service maintenance.',
        category: 'Automotive',
        latitude: 40.7078,
        longitude: -74.0075,
        address: '999 Motor Lane, New York, NY',
        phone: '+1 (555) 890-1234',
        is_premium: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: 'b9',
        profile_id: 'p9',
        business_name: 'Bookworm Paradise',
        bio: 'Cozy bookstore with rare finds and bestsellers. Coffee bar inside!',
        category: 'Retail',
        latitude: 40.7138,
        longitude: -74.0055,
        address: '111 Literary Lane, New York, NY',
        phone: '+1 (555) 901-2345',
        is_premium: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: 'b10',
        profile_id: 'p10',
        business_name: 'The Groove Lounge',
        bio: 'Live music venue featuring local bands. Craft cocktails and great vibes nightly.',
        category: 'Entertainment',
        latitude: 40.7155,
        longitude: -74.0070,
        address: '222 Rhythm Road, New York, NY',
        phone: '+1 (555) 012-3456',
        is_premium: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
];

// Helper to get relative time descriptions
const hoursAgo = (hours: number): string => {
    const date = new Date();
    date.setHours(date.getHours() - hours);
    return date.toISOString();
};

// Sample comments
const createComments = (postId: string, count: number): Comment[] => {
    const sampleComments = [
        { name: 'Sarah M.', content: 'This looks amazing! Can\'t wait to try it 😍' },
        { name: 'John D.', content: 'Been here last week, highly recommend!' },
        { name: 'Emily R.', content: 'What are your hours today?' },
        { name: 'Mike T.', content: 'Best place in the area! 🔥' },
        { name: 'Lisa K.', content: 'Do you offer delivery?' },
        { name: 'Alex B.', content: 'Thanks for the great service yesterday!' },
        { name: 'Chris P.', content: 'Just shared this with my friends' },
        { name: 'Dana W.', content: 'Love the new menu items!' },
    ];

    return sampleComments.slice(0, count).map((c, i) => ({
        id: `${postId}-comment-${i}`,
        post_id: postId,
        user_id: `user-${i}`,
        user_name: c.name,
        content: c.content,
        created_at: hoursAgo(i * 0.5 + 0.1),
    }));
};

// Mock posts (shouts) from businesses with rich media
export const MOCK_POSTS: PostWithBusiness[] = [
    {
        id: 'post1',
        business_id: 'b1',
        content: '☕ FLASH SALE! 50% off all cold brews today only! Beat the heat with our signature Madagascar vanilla cold brew. First 20 customers get a free pastry! 🥐',
        image_url: null,
        images: SAMPLE_IMAGES.coffee.map((url, i) => ({ id: `img-1-${i}`, url, alt: 'Coffee' })),
        likes_count: 127,
        comments_count: 8,
        is_liked: false,
        comments: createComments('post1', 8),
        latitude: 40.7128,
        longitude: -74.006,
        expires_at: hoursAgo(-2),
        created_at: hoursAgo(1),
        business: MOCK_BUSINESSES[0],
    },
    {
        id: 'post2',
        business_id: 'b2',
        content: '🍝 Tonight\'s special: Homemade truffle risotto with wild mushrooms. Limited portions available - reserve your table now!',
        image_url: null,
        images: SAMPLE_IMAGES.food.map((url, i) => ({ id: `img-2-${i}`, url, alt: 'Italian food' })),
        link: {
            url: 'https://bellaitalia.com/reservations',
            title: 'Reserve Your Table - Bella Italia',
            description: 'Book online for dinner tonight. Use code BELLA20 for 20% off.',
            thumbnail_url: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=400&h=300&fit=crop',
            domain: 'bellaitalia.com',
        },
        likes_count: 89,
        comments_count: 5,
        is_liked: true,
        comments: createComments('post2', 5),
        latitude: 40.7145,
        longitude: -74.0035,
        expires_at: hoursAgo(-5),
        created_at: hoursAgo(2),
        business: MOCK_BUSINESSES[1],
    },
    {
        id: 'post3',
        business_id: 'b3',
        content: '💪 New Year, New You! Join today and get your first month FREE plus a complimentary personal training session. Limited spots available!\n\nCheck out our new equipment in action 👇',
        image_url: null,
        video: {
            id: 'vid-1',
            url: SAMPLE_VIDEO,
            thumbnail_url: SAMPLE_IMAGES.gym[0],
            autoplay: false,
        },
        likes_count: 234,
        comments_count: 12,
        is_liked: false,
        comments: createComments('post3', 8),
        latitude: 40.7105,
        longitude: -74.0085,
        expires_at: null,
        created_at: hoursAgo(3),
        business: MOCK_BUSINESSES[2],
    },
    {
        id: 'post4',
        business_id: 'b7',
        content: '🍣 Fresh shipment just arrived! Bluefin tuna from Tsukiji market. Our omakase tonight will be unforgettable. Only 8 seats at the bar.',
        image_url: null,
        images: SAMPLE_IMAGES.sushi.map((url, i) => ({ id: `img-4-${i}`, url, alt: 'Sushi' })),
        likes_count: 312,
        comments_count: 15,
        is_liked: false,
        comments: createComments('post4', 8),
        latitude: 40.7115,
        longitude: -74.0015,
        expires_at: hoursAgo(-3),
        created_at: hoursAgo(4),
        business: MOCK_BUSINESSES[6],
    },
    {
        id: 'post5',
        business_id: 'b5',
        content: '🧘‍♀️ Stressed? Book any massage this week and add a complimentary aromatherapy upgrade. Your mind and body will thank you. #SelfCareSunday',
        image_url: null,
        images: SAMPLE_IMAGES.spa.map((url, i) => ({ id: `img-5-${i}`, url, alt: 'Spa' })),
        link: {
            url: 'https://zenspawellness.com/book',
            title: 'Book Your Relaxation Session',
            description: 'Online booking available 24/7. Same-day appointments welcome.',
            thumbnail_url: 'https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?w=400&h=300&fit=crop',
            domain: 'zenspawellness.com',
        },
        likes_count: 178,
        comments_count: 7,
        is_liked: true,
        comments: createComments('post5', 7),
        latitude: 40.7095,
        longitude: -74.0045,
        expires_at: null,
        created_at: hoursAgo(5),
        business: MOCK_BUSINESSES[4],
    },
    {
        id: 'post6',
        business_id: 'b10',
        content: '🎸 TONIGHT: The Downtown Blues Band live at 9PM! No cover charge before 10PM. $5 craft cocktails during happy hour (6-8PM).\n\nSwipe to see the vibe from last week\'s show 🔥',
        image_url: null,
        images: SAMPLE_IMAGES.music.map((url, i) => ({ id: `img-6-${i}`, url, alt: 'Live music' })),
        likes_count: 445,
        comments_count: 23,
        is_liked: false,
        comments: createComments('post6', 8),
        latitude: 40.7155,
        longitude: -74.0070,
        expires_at: hoursAgo(-1),
        created_at: hoursAgo(6),
        business: MOCK_BUSINESSES[9],
    },
    {
        id: 'post7',
        business_id: 'b4',
        content: '📱 iPhone screen repair special: $49 while you wait! Also offering 15% off all accessories this weekend.',
        image_url: null,
        link: {
            url: 'https://techhub.com/repairs',
            title: 'TechHub Repair Services',
            description: 'Professional phone, tablet, and laptop repairs. Most repairs done in under an hour.',
            thumbnail_url: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400&h=300&fit=crop',
            domain: 'techhub.com',
        },
        likes_count: 67,
        comments_count: 4,
        is_liked: false,
        comments: createComments('post7', 4),
        latitude: 40.7158,
        longitude: -74.0095,
        expires_at: hoursAgo(-24),
        created_at: hoursAgo(8),
        business: MOCK_BUSINESSES[3],
    },
    {
        id: 'post8',
        business_id: 'b6',
        content: '👗 Just dropped: Our new sustainable summer collection! Made with 100% organic cotton. Shop now and plant a tree with every purchase 🌳\n\nSwipe through our lookbook →',
        image_url: null,
        images: SAMPLE_IMAGES.fashion.map((url, i) => ({ id: `img-8-${i}`, url, alt: 'Fashion' })),
        likes_count: 523,
        comments_count: 31,
        is_liked: true,
        comments: createComments('post8', 8),
        latitude: 40.7168,
        longitude: -74.0025,
        expires_at: null,
        created_at: hoursAgo(10),
        business: MOCK_BUSINESSES[5],
    },
    {
        id: 'post9',
        business_id: 'b9',
        content: '📚 Author signing event this Saturday! Local mystery writer Jane Smith will be here 2-4PM. Free coffee and cookies. RSVP recommended.',
        image_url: null,
        images: SAMPLE_IMAGES.books.map((url, i) => ({ id: `img-9-${i}`, url, alt: 'Books' })),
        link: {
            url: 'https://bookwormparadise.com/events',
            title: 'Upcoming Events - Bookworm Paradise',
            description: 'RSVP for the Jane Smith book signing. Limited seats available.',
            thumbnail_url: 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=400&h=300&fit=crop',
            domain: 'bookwormparadise.com',
        },
        likes_count: 156,
        comments_count: 9,
        is_liked: false,
        comments: createComments('post9', 8),
        latitude: 40.7138,
        longitude: -74.0055,
        expires_at: null,
        created_at: hoursAgo(12),
        business: MOCK_BUSINESSES[8],
    },
    {
        id: 'post10',
        business_id: 'b8',
        content: '🚗 Winter tire special! Full set installation for $79 (normally $120). Includes free tire rotation. Book before the snow hits!',
        image_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop',
        likes_count: 45,
        comments_count: 2,
        is_liked: false,
        comments: createComments('post10', 2),
        latitude: 40.7078,
        longitude: -74.0075,
        expires_at: null,
        created_at: hoursAgo(15),
        business: MOCK_BUSINESSES[7],
    },
    {
        id: 'post11',
        business_id: 'b1',
        content: '🎄 Holiday blend is HERE! Our limited edition Gingerbread Spice Latte is back by popular demand. Available while supplies last!',
        image_url: 'https://images.unsplash.com/photo-1512568400610-62da28bc8a13?w=800&h=600&fit=crop',
        likes_count: 289,
        comments_count: 14,
        is_liked: true,
        comments: createComments('post11', 8),
        latitude: 40.7128,
        longitude: -74.006,
        expires_at: null,
        created_at: hoursAgo(20),
        business: MOCK_BUSINESSES[0],
    },
    {
        id: 'post12',
        business_id: 'b2',
        content: '🎉 We just got featured in NY Magazine\'s Best Italian Restaurants! Come celebrate with us - free dessert with any entrée tonight!',
        image_url: null,
        link: {
            url: 'https://nymag.com/best-restaurants/italian',
            title: 'Best Italian Restaurants in NYC - NY Magazine',
            description: 'Our annual roundup of the city\'s finest Italian dining experiences.',
            thumbnail_url: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=400&h=300&fit=crop',
            domain: 'nymag.com',
        },
        likes_count: 567,
        comments_count: 42,
        is_liked: false,
        comments: createComments('post12', 8),
        latitude: 40.7145,
        longitude: -74.0035,
        expires_at: hoursAgo(-0.5),
        created_at: hoursAgo(22),
        business: MOCK_BUSINESSES[1],
    },
];

// Function to get mock businesses (can be filtered by bounds later)
export function getMockBusinesses(): BusinessDetails[] {
    return MOCK_BUSINESSES;
}

// Function to get mock posts
export function getMockPosts(limit?: number): PostWithBusiness[] {
    const posts = [...MOCK_POSTS].sort(
        (a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime()
    );
    return limit ? posts.slice(0, limit) : posts;
}
